/* state.minMaxPitch Actions */
export const MIN_PITCH_SET = 'MIN_PITCH_SET';
export const MAX_PITCH_SET = 'MAX_PITCH_SET';

/* state.bpm Actions */
export const BPM_SET = 'BPM_SET';

/* state.visualization Actions */
export const VISUALIZATION = {
  TOGGLE: 'VISUALIZATION_TOGGLE',
  ANIMATED: 'VISUALIZATION_ANIMATE',
};

/* state.synth Actions */
export const SYNTH = {
  VOLUME_SET: 'SYNTH_VOLUME_SET',
  OSCILLATOR_SET: 'SYNTH_OSCILLATOR_SET',
  CHORUS_TOGGLE: 'SYNTH_CHORUS_TOGGLE',
  DISTORTION_TOGGLE: 'SYNTH_DISTORTION_TOGGLE',
  JCREVERB_TOGGLE: 'SYNTH_JCREVERB_TOGGLE',
  FREEVERB_TOGGLE: 'SYNTH_FREEVERB_TOGGLE',
  AUTOWAH_TOGGLE: 'SYNTH_AUTOWAH_TOGGLE',
};
